name: my actions

on:
  push:
    branches: main  
  watch:
    types: [ started ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: pthome 签到
        id: pthome
        env:
          COOKIE: ${{secrets.PTHOME_COOKIE}}
        run: |
          echo "::set-output name=result::pthome \n pthome test \n"

      - name: 360有钱 签到
        id: youqian
        env:
          COOKIE: ${{secrets.YOUQIAN_COOKIE}}
        run: 
          echo "::set-output name=result::360有钱 \r\n youqian test \r\n"

      - name: 生成任务报告        
        id: report
        run: |
          output="${{steps.pthome.outputs.result}} ${{steps.youqian.outputs.result}}"
          output="${output//'%'/'%25'}"
          output="${output//$'\n'/'%0A'}"
          output="${output//$'\r'/'%0D'}"
          echo "::set-output name=result::$output"
        

      - name: 发送邮件通知
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.88.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: github action 任务报告
          body: ${{steps.report.outputs.result}}
          to: ${{secrets.MAIL_TO}}
          from: github action
          content_type: text/html

