name: my actions

on:
  push:
    branches: main
  watch:
    types: [ started ]
  schedule:
    - cron: 1 22 * * * #runs at 0:01 UTC everyday


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # - id: pthome
      #   env:
      #     COOKIE: ${{secrets.PTHOME_COOKIE}}
      #   run: |
      #     output=$(python pthome.py)
      #     output="${output//$'\n'/<br>}"
      #     echo "::set-output name=result::$output"

      # - id: youqian
      #   env:
      #     COOKIE: ${{secrets.YOUQIAN_COOKIE}}
      #   run: |
      #     output=$(python 360youqian.py)
      #     output="${output//$'\n'/<br>}"
      #     echo "::set-output name=result::$output"

      - id: elecfans
        env:
          COOKIE: ${{secrets.ELECFANS_COOKIE}}
        run: |
          output=$(python elecfans.py)
          output="${output//$'\n'/<br>}"
          echo "::set-output name=result::$output"

      - name: 拼接输出字符串
        id: report
        run: |
          output="${{steps.pthome.outputs.result}}<br>"
          output=$output"${{steps.youqian.outputs.result}}<br>"
          echo "::set-output name=result::$output"

      - name: 发送邮件通知
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.88.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: github action 任务报告
          body: ${{steps.report.outputs.result}}
          to: ${{secrets.MAIL_TO}}
          from: github action
          content_type: text/html

